# -*- coding: utf-8 -*-
"""nonferrous_daily_price.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JcXKEs9dr5DSrXvYSg4KIhhhoDV-mzll
"""

# kotra api 연동코드 (2023,4,5)

# 6대 원자재 (hhi큰) 물가 데이터

import os
import urllib.parse
import requests
import pandas as pd

def fetch_nonferrous_prices():
    # 1. 환경변수에서 API 키를 가져온다 (하드코딩 금지 — .env.local 참조)
    raw_key = os.environ.get("DATA_GO_KR_KEY", "")  # .env.local 에서 주입. 기본값에 실제 키를 넣지 말 것.

    # URL 인코딩 변환 (이미 %2B 형태라면 그대로 사용, 디코딩 상태라면 인코딩)
    if "%" in raw_key:
        service_key = raw_key
    else:
        service_key = urllib.parse.quote(raw_key)

    # Base URL 및 Endpoint
    base_url = "https://api.odcloud.kr/api/15151558/v1/uddi:e377eebd-ce29-4807-a362-90f4a0f5c486" # 올바른 엔드포인트로 수정

    params = {
        "page": 1,
        "perPage": 100,
        "serviceKey": urllib.parse.unquote(service_key)  # requests는 자동으로 인코딩하므로 디코딩 키 전달
    }

    headers = {
        "accept": "application/json",
        "Authorization": f"Infuser {service_key}"
    }

    print("API 요청 중...")
    response = requests.get(base_url, params=params) # base_url 변수를 사용하도록 수정

    if response.status_code == 200:
        data = response.json()
        items = data.get("data", [])

        df = pd.DataFrame(items)
        print(f"총 {len(df)}건의 데이터를 수집했습니다.")

        # CSV 및 Parquet으로 저장
        df.to_csv("nonferrous_daily_price.csv", index=False, encoding="utf-8-sig")
        df.to_parquet("nonferrous_daily_price.parquet", index=False)
        print("저장 완료: nonferrous_daily_price.csv / .parquet")

        return df
    else:
        print(f"호출 실패 (상태코드: {response.status_code})")
        print(response.text)
        return None

if __name__ == "__main__":
    fetch_nonferrous_prices()